Fix scrollcon search
vlmnst/proyecto-final pull request #106
Opened 2022-07-23 18:59 UTC by vlmnst

2022-07-23 19:12 UTC, Chelolb approved these changes
ok

2022-07-23 19:18 UTC, userMauro requested changes
rompe el re-renderizado de los productos del admin

2022-07-23 21:37 UTC, vlmnst commented
solucionado ^^

2022-07-24 15:26 UTC, CrisValhas approved these changes
obviooo

2022-07-24 21:38 UTC, Erick-Osterling approved these changes
ok

2022-07-24 22:11 UTC, Erick-Osterling approved these changes
ok

2022-07-24 22:42 UTC, CrisValhas approved these changes
probe

2022-07-25 02:02 UTC, Amnaujj approved these changes

2022-07-25 02:02 UTC, userMauro approved these changes
okkk

2022-07-25 02:02 UTC, Cronm25 approved these changes

2022-07-25 02:02 UTC, merged