Comp product card
vlmnst/proyecto-final pull request #16
Opened 2022-07-06 21:01 UTC by Erick-Osterling

añadi package-llock.json a gitignore (primer commit)

se hizo el componente de product-card

2022-07-06 21:04 UTC, Cronm25 approved these changes

2022-07-06 21:06 UTC, vlmnst approved these changes

2022-07-06 21:08 UTC, Chelolb approved these changes
ok

2022-07-06 21:18 UTC, CrisValhas requested changes
-no se muestra el name del producto
-styles.description: viene del back con propiedades .... se intenta leer cuando debería mapear las propiedades que tenga asignadas para mostrarlas. 
- en caso de tener offer mayor a 0 debería mostrarse la oferta en la tarjeta.

2022-07-06 22:34 UTC, Cronm25 approved these changes

2022-07-06 22:35 UTC, Cronm25 approved these changes

2022-07-07 00:35 UTC, Erick-Osterling commented
> -no se muestra el name del producto -styles.description: viene del back con propiedades .... se intenta leer cuando debería mapear las propiedades que tenga asignadas para mostrarlas.
> 
> * en caso de tener offer mayor a 0 debería mostrarse la oferta en la tarjeta.

Listo!

2022-07-07 13:48 UTC, CrisValhas approved these changes
aprove

2022-07-07 13:49 UTC, merged